name: "Verify forc version"

on:
  pull_request:
    branches:
      - master

jobs:
  verify-forc-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: CI Setup
        uses: ./.github/actions/ci-setup

      - name: Verify forc version
        run: pnpm forc:verify

      - name: Bump and Collect Versions
        run: |
          echo "CURRENT_VERSION=v$(sed -nE 's/^\s*"version": "(.*?)",$/\1/p' packages/fuels/package.json)" >> $GITHUB_ENV
          pnpm changeset version
          echo "RELEASE_VERSION=v$(sed -nE 's/^\s*"version": "(.*?)",$/\1/p' packages/fuels/package.json)" >> $GITHUB_ENV
          echo "COMMIT_MSG=$(git log -n 1 --format=%B)" >> $GITHUB_ENV
          git reset --hard
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        if: ${{ env.RELEASE_VERSION != env.CURRENT_VERSION && !startsWith(env.COMMIT_MSG, "ci(changesets)") }}
        run: echo $COMMIT_MSG
        env:
          COMMIT_MSG: ${{ env.COMMIT_MSG }}
